apiVersion: v1
kind: Pod
metadata:
  name: nextcloud
  labels:
    app: nextcloud
spec:
  restartPolicy: Always
  containers:
  - image: docker.io/library/postgres:alpine
    name: nextcloud-db
    env:
    - name: POSTGRES_DB
      value: nextcloud
    - name: POSTGRES_PASSWORD
      value: nextcloud
    - name: POSTGRES_USER
      value: nextcloud
    securityContext:
      allowPrivilegeEscalation: true
      privileged: false
      readOnlyRootFilesystem: false
    volumeMounts:
    - mountPath: /var/lib/postgresql/data
      name: mnt-nextcloud-db

  - image: docker.io/library/redis:alpine
    name: nextcloud-redis
    args:
    - redis-server
    - --requirepass
    - redis
    securityContext:
      allowPrivilegeEscalation: true
      privileged: false
      readOnlyRootFilesystem: false
 
  - image: docker.io/library/nginx:alpine
    name: nextcloud-nginx
    ports:
    - containerPort: 80
      hostPort: 8081
      protocol: TCP
    securityContext:
      allowPrivilegeEscalation: true
      privileged: false
      readOnlyRootFilesystem: false
    volumeMounts:
    - mountPath: /etc/nginx/nginx.conf
      name: mnt-nextcloud-nginx-conf
      readOnly: true
    - mountPath: /var/www/html
      name: mnt-nextcloud-html
      readOnly: true

  - image: docker.io/library/nextcloud:fpm-alpine
    name: nextcloud-cron
    command:
    - /cron.sh
    env:
    securityContext:
      allowPrivilegeEscalation: true
      privileged: false
      readOnlyRootFilesystem: false
    volumeMounts:
    - mountPath: /var/www/html/data
      name: mnt-nextcloud-data
    - mountPath: /var/www/html
      name: mnt-nextcloud-html

  - image: docker.io/library/nextcloud:fpm-alpine
    name: nextcloud-app
    env:
    - name: POSTGRES_HOST
      value: localhost
    - name: POSTGRES_DB
      value: nextcloud
    - name: POSTGRES_USER
      value: nextcloud
    - name: POSTGRES_PASSWORD
      value: nextcloud
    - name: REDIS_HOST
      value: localhost
    - name: REDIS_HOST_PASSWORD
      value: redis
    securityContext:
      allowPrivilegeEscalation: true
      privileged: false
      readOnlyRootFilesystem: false
    volumeMounts:
    - mountPath: /var/www/html/data
      name: mnt-nextcloud-data
    - mountPath: /var/www/html
      name: mnt-nextcloud-html
        
  volumes:
  - name: mnt-nextcloud-data
    hostPath:
      path: /mnt/nextcloud/data
      type: DirectoryOrCreate

  - name: mnt-nextcloud-db
    hostPath:
      path: /mnt/nextcloud/db
      type: DirectoryOrCreate

  - name: mnt-nextcloud-nginx-conf
    hostPath:
      path: /mnt/nextcloud/nginx/nginx.conf
      type: File
  
  - name: mnt-nextcloud-html
    hostPath:
      path: /mnt/nextcloud/html
      type: DirectoryOrCreate

